server:
  port: 8081

spring:
  application:
    name: hospital-service

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_db
    username: cmis_user
    password: cmis_pass
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: hospital-pool

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.zhsf: INFO
